### ISSUE TITLE
FILE_UPLOAD=localの際にファイルがアップロードできない

### ISSUE THREAD

**Issue by mose19800115** [weseek/crowi-plus-docker-compose#4]
Environment
------------

- [OS]Ubuntu 16.04.2 LTS
- [crowi-plus] 2.0.0
- [Docker] 17.06.0-ce
- [docker-compose] 1.14.0

How to reproduce? (再現手順)
---------------------------

1. ページを編集する
1. ファイルをブラウザにドラッグ＆ドロップする

What happens? (症状)
---------------------

- symptom
(Uploading file...)の文字列のみ挿入される

What is the expected result? (期待される動作)
-------------------------------------------

- expected result
ファイルがアップロードされ、自動的にリンクが生成される

Note
----

- /data/uploadsディレクトリを作成すると問題解消
    - /data/uploadsが存在していない
    - build時のmkdirでエラーになっている様子はない

**Comment by yuki-takei** [comment]
ご報告ありがとうございます。近日中に確認します。

**Comment by yuki-takei** [comment]
@mose19800115 
ご報告いただいた症状、こちらでも確認しました。

一旦 crowi-plus-docker-comose の方ではなく、 weseek/crowi-plus-docker 側で対策を施した docker image v2.0.5 をリリースしました。お試しください。

**Comment by mose19800115** [comment]
@yuki-takei 
早速のご対応ありがとうございます。
問題なく動作することが確認できました。
これから使い倒したいと思います。
